# Generated by Django 5.0.6 on 2024-06-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('imagen', models.ImageField(null=True, upload_to='Imagenes/', verbose_name='Imagen')),
                ('descripción', models.TextField(null=True, verbose_name='Descripción')),
            ],
        ),
    ]
