# Generated by Django 5.0.6 on 2024-07-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_rename_marca_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_genero', models.AutoField(db_column='idContacto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
                ('mensaje', models.CharField(max_length=200)),
            ],
        ),
    ]
