# Generated by Django 5.0.6 on 2024-07-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_rename_clientes_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=20, verbose_name='Apellido')),
                ('direccion', models.TextField(max_length=225, verbose_name='Direccion')),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
