# Generated by Django 5.0.6 on 2024-07-06 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_clientes_delete_cliente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Clientesss',
        ),
    ]
