# Generated by Django 5.0.6 on 2024-07-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_rename_clientes_clientesss'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=20, verbose_name='Marca')),
                ('categoria', models.CharField(max_length=20, verbose_name='Categoria')),
                ('precio', models.TextField(max_length=225, verbose_name='Precio')),
            ],
        ),
    ]
