# Generated by Django 5.0.6 on 2024-07-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
    ]
