# Generated by Django 5.0.6 on 2024-07-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=250, verbose_name='Producto')),
                ('cantidad', models.CharField(max_length=250, verbose_name='Cantidad')),
            ],
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='Monto',
            new_name='monto',
        ),
        migrations.AlterField(
            model_name='factura',
            name='nombre',
            field=models.CharField(max_length=250, verbose_name='Nombre'),
        ),
    ]
